name: Deploy pages
on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
    
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
    
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                node-version: '20.8.1'
                
            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build -- --base /weighted-likelihood-filter-talk/
              
            - name: Print files in main folder
              run: ls -lah
              
            - name: Print files in main folder
              run: ls -lah dist

            - name: Print files in main folder
              run: ls -lah dist/assets
            
            - uses: actions/configure-pages@v3

            - uses: actions/upload-pages-artifact@v1
              with:
                path: dist
      
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v2
